# Generated by Django 3.1.2 on 2020-10-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('inflow', 'inflow'), ('outflow', 'outflow')], max_length=10)),
                ('category', models.CharField(choices=[('groceries', 'groceries'), ('transfer', 'transfer'), ('salary', 'salary'), ('rent', 'rent'), ('other', 'other'), ('savings', 'savings')], max_length=20)),
                ('date', models.DateField()),
                ('account', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user')),
            ],
        ),
    ]
